In [1]:
import pandas as pd
import numpy as np

In [2]:
# Task 1 - Creating dataframes and saving as csv

    # Project DataFrame

project_df = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A003","A005"],
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8",
                "Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
    "Cost": [1002000,2000000,4500000,5500000,np.nan,680000,400000,350000,np.nan,300000,2000000,1000000,300000,2000000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed",
               "Ongoing","Finished","Failed","Ongoing","Finished","Finished"]
})
    # Saving as csv

project_df.to_csv("project_df.csv")

    #Employee DataFrame

employee_df = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Name": ["John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],
    "Gender": ["M","F","M","F","F"],
    "City": ["Paris","London","Berlin","Newyork","Madrid"],
    "Age": [25,27,29,31,30]
})

    # Saving as csv
    
employee_df.to_csv("employee_df.csv")

    # Seniority level DataFrame

seniority_df = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Designation Level": [2,2,3,2,3]
})

    # Saving as csv

seniority_df.to_csv("seniority_df.csv")

In [3]:
# loading saved csv files
project_ld = pd.read_csv("project_df.csv", index_col=0)
employee_ld = pd.read_csv("employee_df.csv", index_col=0)
seniority_ld = pd.read_csv("seniority_df.csv", index_col=0)

In [4]:
# Projetc DataFrame after loading back
project_ld

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A003  Project 13   300000.0  Finished
13  A005  Project 14  2000000.0  Finished

In [5]:
# employee dataframe after loading back
employee_ld

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [6]:
# seniority level dataframe after loading back
seniority_ld

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [7]:
# Task 2 - reassining costs to blanks using running averages

for i in range(len(project_ld)):
    if pd.isna(project_ld.loc[i, "Cost"]):
        # Look at all previous rows in Cost column
        prev_values = project_ld.loc[:i-1, "Cost"].dropna()
        if len(prev_values) > 0:
            project_ld.loc[i, "Cost"] = prev_values.mean()
updated_values = project_ld.loc[4:8].drop(project_ld.index[5:8])
updated_values

     ID    Project       Cost    Status
4  A005  Project 5  3250500.0  Finished
8  A001  Project 9  2210312.5   Ongoing

In [8]:
# Projetc DataFrame after replacing blanks
project_ld

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5  3250500.0  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9  2210312.5   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A003  Project 13   300000.0  Finished
13  A005  Project 14  2000000.0  Finished

In [9]:
# Task 3 - Spliting name column of employee dataframe

    # Spliting Name column

employee_ld[["First Name","Last Name"]]= employee_ld["Name"].str.split(' ',expand=True, n=1)

    # deleting Name column

employee_ld = employee_ld.drop(columns=["Name"])

employee_ld

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [10]:
# Task 4 - Joining all 3 dataframes into one

Final = project_ld.merge(employee_ld, on ="ID").merge(seniority_ld, on = "ID")
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A003,Project 13,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3
13,A005,Project 14,2000000.0,Finished,F,Madrid,30,Amy,Johny,3

In [11]:
# Task 5 - Creating Bonus column

Final["Bonus"]= np.where(Final["Status"]=="Finished",Final["Cost"]*0.05,0)
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2,0.0
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3,0.0
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2,0.0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A003,Project 13,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
13,A005,Project 14,2000000.0,Finished,F,Madrid,30,Amy,Johny,3,100000.0

In [12]:
# Sorting the Final DataFrame by ID in ascending order

Final = Final.sort_values(by="ID", ascending=True).reset_index(drop=True)

Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0.0
2,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2,0.0
3,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
4,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2,0.0
5,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
6,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3,0.0
7,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
8,A003,Project 13,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
9,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
10,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
11,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
12,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000.0
13,A005,Project 14,2000000.0,Finished,F,Madrid,30,Amy,Johny,3,100000.0

In [13]:
# Task 6 - Demoting employees with failed projects

    # Creating updated designation Level - row-wise

Final["Updated Designation Level"]= np.where(Final["Status"]=="Failed",Final["Designation Level"]-1,Final["Designation Level"])

    # Grouping the row-wise updated designation level to generate one updated designation level per employee

new_emp_lvl= Final.groupby("ID")["Updated Designation Level"].min().reset_index()

    # Joing the employee-wise updated designation level to the Final DataFrame

Final1 = Final.drop(columns=["Updated Designation Level"])
Final = Final1.merge(new_emp_lvl, on="ID", how="left")

# Code to drop level 4 (if any) in updated designation level

Final = Final[Final["Updated Designation Level"] != 4]

Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus,Updated Designation Level
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0,1
1,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0.0,1
2,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2,0.0,1
3,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0.0,1
4,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2,0.0,1
5,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0,2
6,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3,0.0,2
7,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0,2
8,A003,Project 13,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0,2
9,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0,2
10,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0,2
11,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0,3
12,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000.0,3
13,A005,Project 14,2000000.0,Finished,F,Madrid,30,Amy,Johny,3,100000.0,3

In [14]:
# Task 7 - Adding prefix to first name column and droping gender column

    # Adding Prefix

Final["First Name"] = np.where(Final["Gender"]=="M","Mr. "+Final["First Name"],"Mrs. "+Final["First Name"])

    # Dropping Gender column

Final = Final.drop(columns=["Gender"])

Final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus,Updated Designation Level
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100.0,1
1,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,0.0,1
2,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,2,0.0,1
3,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0,1
4,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,2,0.0,1
5,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0,2
6,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,3,0.0,2
7,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0,2
8,A003,Project 13,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0,2
9,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0,2
10,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0,2
11,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,3,162525.0,3
12,A005,Project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,20000.0,3
13,A005,Project 14,2000000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,100000.0,3

In [15]:
# Task 8 - Pormote all employee above 29 years by 1 level

Final["Updated Designation Level"] = Final.apply(
    lambda row: row["Updated Designation Level"] + 1 if row["Age"] > 29 else row["Updated Designation Level"],
    axis=1)
Final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus,Updated Designation Level
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100.0,1
1,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,0.0,1
2,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,2,0.0,1
3,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0,1
4,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,2,0.0,1
5,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0,2
6,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,3,0.0,2
7,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0,2
8,A003,Project 13,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0,2
9,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0,3
10,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0,3
11,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,3,162525.0,4
12,A005,Project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,20000.0,4
13,A005,Project 14,2000000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,100000.0,4

In [17]:
# Task 8 - Version 2 - where we have deleted level 4 as instructed in task 6

Final_without_4 = Final[Final["Updated Designation Level"] != 4]

Final_without_4

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus,Updated Designation Level
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100.0,1
1,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,0.0,1
2,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,2,0.0,1
3,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0,1
4,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,2,0.0,1
5,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0,2
6,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,3,0.0,2
7,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0,2
8,A003,Project 13,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0,2
9,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0,3
10,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0,3

In [18]:
# Task 9 - Total cost of projects per employee

TotalProjCost = pd.pivot_table(Final,index=["ID","First Name"],values="Cost")

# Renaming Cost column

TotalProjCost = TotalProjCost.rename(columns={"Cost": "Total Cost"})

TotalProjCost

                 Total Cost
ID   First Name
A001 Mr. John     1737437.5
A002 Mrs. Alice   1340000.0
A003 Mr. Tom      1362500.0
A004 Mrs. Nina    3250000.0
A005 Mrs. Amy     1883500.0

In [19]:
# Task 10 - Version 4 - Employee details from Final dataframe - without print command(as it does not look presentable with print command)

emp_with_o = Final[Final["City"].str.contains("o")]
print("Employee details where city name has 'o' :\n")
emp_with_o

Employee details where city name has 'o' :

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus,Updated Designation Level
3,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0,1
4,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,2,0.0,1
9,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0,3
10,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0,3

In [20]:
# Task 10 - Version 3 - Employee details from Final dataframe

emp_with_o = Final[Final["City"].str.contains("o")]
print("Employee details where city name has 'o' :")
print(emp_with_o)

Employee details where city name has 'o' :
      ID     Project       Cost   Status     City  Age  First Name  Last Name  \
3   A002   Project 2  2000000.0  Ongoing   London   27  Mrs. Alice  Luxumberg
4   A002   Project 6   680000.0   Failed   London   27  Mrs. Alice  Luxumberg
9   A004   Project 4  5500000.0  Ongoing  Newyork   31   Mrs. Nina      Adgra
10  A004  Project 12  1000000.0  Ongoing  Newyork   31   Mrs. Nina      Adgra

    Designation Level  Bonus  Updated Designation Level
3                   2    0.0                          1
4                   2    0.0                          1
9                   2    0.0                          3
10                  2    0.0                          3

In [21]:
# Task 10 - Version 2 - Employee details from updated employee dataframe

emp_with_o = employee_ld[employee_ld["City"].str.contains("o")]
print("Employee details where city name has 'o':\n",emp_with_o)

Employee details where city name has 'o':
      ID Gender     City  Age First Name  Last Name
1  A002      F   London   27      Alice  Luxumberg
3  A004      F  Newyork   31       Nina      Adgra

In [22]:
# Task 10 - Version 1 - Employee details from source employee dataframe

emp_with_o = employee_df[employee_df["City"].str.contains("o")]
print("Employee details where city name has 'o':\n",emp_with_o)

Employee details where city name has 'o':
      ID             Name Gender     City  Age
1  A002  Alice Luxumberg      F   London   27
3  A004       Nina Adgra      F  Newyork   31